
#scaled frequency range
initi_freq: 2
numbr_freq: 100
final_freq: 200

parti_freq: 100

#speed ratio
skr: 993
#density ratio
sdr: 800

spec_band: 0.2
spec_size: 2500
ref_freq: 1000000
    
# Display_time_step_ratio 
dtsr: 0 # 0 if not to display
# Offset data matrix
offset: 0 # 0 if not to offset

CONVE_MOD: 'Pr5'