#model proportional scale 
MODEL_SCL: 2
#frequency range as fraction
FREQF_INI: .01
FREQF_DEL: 100
FREQF_FIN: 1
#frequency index update
FREQU_INI: 1
FREQU_FIN: 100
#speed ratio
RATSP_INI: 993
RATSP_DEL: 1
RATSP_FIN: 993
#density ratio
RATDS_INI: 800
RATDS_DEL: 1
RATDS_FIN: 800
#sensitivity ratio
RATPS_INI: 100 
RATPS_DEL: 1
RATPS_FIN: 100
#x grid length
GRIDX_INI: .25
GRIDX_DEL: 1
GRIDX_FIN: .25
#y grid length
GRIDY_INI: .25
GRIDY_DEL: 1
GRIDY_FIN: .25
#x grid centre
CENTX_INI: 64
CENTX_DEL: 1
CENTX_FIN: 64
#y grid centre
CENTY_INI: 33.557046979865774
CENTY_DEL: 1
CENTY_FIN: 33.557046979865774
# SCALE WAVELENGTH
RADIA_SIZ: 1
# CENTI SOURCE PER WAVELENGHT
ELEME_WAV: 500
#PISTON TX RANGE
PISTO_VCT: 64
#PISTON RX RANGE
PISTO_VCR: 64
#PISTON SIZE
PISTO_RAD: 12.7852
#PISTON CENTRE
PISTO_CEN: 33.557046979865774
PISTO_DST: 128
#INTERF CENTRE
INTER_CEN: 33.557046979865774
#ATTENUANTIO COEFFICIENT
ATTEN_RAT: 0.0005
CONVE_MOD: 'Pr5'