#model proportional scale 
MODEL_SCL: .5
#frequency range as fraction
FREQF_INI: .01
FREQF_DEL: 100
FREQF_FIN: 1
#frequency index update
FREQU_INI: 1
FREQU_FIN: 100
#speed ratio
RATSP_INI: 23
RATSP_DEL: 1
RATSP_FIN: 23
#density ratio
RATDS_INI: 1
RATDS_DEL: 1
RATDS_FIN: 1
#sensitivity ratio
RATPS_INI: 100 
RATPS_DEL: 1
RATPS_FIN: 100
#x grid length
GRIDX_INI: 1
GRIDX_DEL: 1
GRIDX_FIN: 1
#y grid length
GRIDY_INI: 1
GRIDY_DEL: 1
GRIDY_FIN: 1
#x grid centre
CENTX_INI: 168
CENTX_DEL: 1
CENTX_FIN: 168
#y grid centre
CENTY_INI: 168
CENTY_DEL: 1
CENTY_FIN: 168
# SCALE WAVELENGTH
RADIA_SIZ: 1
# CENTI SOURCE PER WAVELENGHT
ELEME_WAV: 500
#PISTON TX RANGE
PISTO_VCT: 248
#PISTON RX RANGE
PISTO_VCR: 248
#PISTON SIZE
PISTO_RAD: 6.8 # 6.75219 #0.2
#PISTON ANGLE
PISTO_ANG: 0
#PISTON CENTRE
PISTO_CEN: 168 # 336 #8
PISTO_DST: 168 # 336 #8
#INTER ANGLE
INTER_ANG: 0
#INTERF CENTRE
INTER_CEN: 168
# TANK_RAD
TANK_RAD: 168 # 336 #8
#ATTENUANTIO COEFFICIENT
ATTEN_RAT: 0.00000000025 # 0.000005
CONVE_MOD: 'horizontal'